#file: noinspection HttpUrlsUsage,SpellCheckingInspection
networks:
  internal:
  minio:
  traefik-proxy:
  #  external: true

x-minio-common: &minio-common
  image: quay.io/minio/minio:latest
  env_file:
    - configs/.minio.env
  networks:
    - minio
  healthcheck:
    test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/ready" ]
    interval: 10s
    timeout: 5s
    retries: 5
    start_period: 10s
  command: server --console-address ":9001" /data


services:
  postgres:
    image: docker.io/library/postgres:17-bookworm
    container_name: mietmiez-postgres
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 3s
      timeout: 5s
      retries: 5
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - internal
    env_file:
      - configs/.postgres.env

  backend:
    image: localhost/mietmiez_backend:latest
    build:
      context: backend
    container_name: mietmiez-backend
    restart: always
    tty: true
    healthcheck:
      test: [ "CMD", "wget --spider --no-verbose --tries=1 http://localhost:8080/v1/health" ]
      interval: 5s
      timeout: 10s
      retries: 5
    depends_on:
      postgres:
        condition: service_healthy
      minio1:
        condition: service_healthy
    networks:
      - internal
      - minio
    ports:
      - "8080:8080"
    volumes:
      - ./openapi/mietmiez.yml:/app/openapi_v1.yml
      - ./configs/static/about.json:/app/about.json
      - ./configs/static/email_activateUser.html:/app/email_activateUser.html
      - ./configs/static/email_resetPassword.html:/app/email_resetPassword.html
    env_file:
      - configs/.minio.env
      - configs/.postgres.env
      - configs/.backend.env
    labels:
      - "traefik.enable=false"
      - "traefik.http.routers.mietmiez-backend.rule=Host(`api.mietmiez.de`)"
      - "traefik.http.routers.mietmiez-backend.service=mietmiez-backend"
      - "traefik.http.services.mietmiez-backend.loadbalancer.server.port=8080"

  frontend:
    image: localhost/mietmiez_frontend:latest
    build:
      context: frontend
    container_name: mietmiez-frontend
    restart: always
    healthcheck:
      test: [ "CMD", "wget --spider --no-verbose --tries=1 http://localhost:3000" ]
      interval: 5s
      timeout: 10s
      retries: 5
#    depends_on:
#      backend:
#        condition: service_healthy
#      postgres:
#        condition: service_healthy
    networks:
      - internal
      - traefik-proxy
    ports:
      - "3000:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mietmiez-frontend.rule=Host(`mietmiez.de`)"
      - "traefik.http.routers.mietmiez-frontend.service=mietmiez-frontend"
      - "traefik.http.services.mietmiez-frontend.loadbalancer.server.port=3000"
    env_file:
    - configs/.frontend.env

  minio1:
    <<: *minio-common
    container_name: minio1
    hostname: minio1
    volumes:
      - ./data/minio1:/data
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Web Console (Admin UI)
    networks:
      - traefik-proxy
      - minio
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minio-api.rule=Host(`minio.mietmiez.de`)"
      - "traefik.http.routers.minio-api.service=minio-api"
      - "traefik.http.services.minio-api.loadbalancer.server.port=9000"
